@startuml PMO IT
title "Flow Process Detail Project (BizReq)"

actor "user" as user #Yellow
boundary "Project Menu" as ui
boundary "Detail Page" as ui2
control "api" as api
database "DB_PMO_IT" as DB_PMO_IT

autonumber
user -> ui : Click Detail at row (table)
activate ui
ui -> ui2 : Transfer data with data selected
deactivate ui
activate ui2
ui2 -> ui2 : Hide all button & disable all field
ui2 -> api : request data with parameter id_request
deactivate ui2
activate api
api -> DB_PMO_IT : Get data
deactivate api
activate DB_PMO_IT
note left of DB_PMO_IT
    Get field "requestNumber", "itBackground", "goalsAndObjective",
    "currentProcess", "futureProcess",
    "status", "state", "ictNumber", "ictDate","priority",
    "benefitQualitative", "reasonForUrgency", "solutionProposed",
    "budget", "budgetType", "referenceApplication"
    from table "request_project"

    Get field "description", "value",
    "quantity", "totalValue"
    from table "benefit_quantitative"

    Get field "title", "url"
    from table "reference_procedure"

    Get field "description", "impact", "mitigation"
    from table "risk_hazard"

    Get field "name", "presentTitle",  "reason", "dateReason"
    from table "remark_log"

    Get all field from table "master_status"

    Get all field from table "project_type"

    Get field "review_status", "reason", "businessImplementation", "itSolution",
    from table "fill_by_it"

    Get all field from table "project_scale"

    Get field "link", "status", "id_document_type"
    from table "document"

    Get all field from table "assignment"

    filter by id_request_project
end note
api <- DB_PMO_IT : response data
deactivate DB_PMO_IT

activate api
api -> ui2 : return json
deactivate api
activate ui2
ui2 -> ui2 : Show button if
note right of ui2
    if login as user
    not show anything button
    if login as IT Department
    show button "Save"
endnote
ui2 -> user : Display
deactivate ui2

@enduml