@startuml PMO IT
title "Flow Process Detail Project (CRF) (1)"

actor "user" as user #Yellow
boundary "Project Menu" as ui
boundary "Detail Page" as ui2
control "api" as api
database "DB_PMO_IT" as DB_PMO_IT

autonumber
user -> ui : Click Detail at row (table)
activate ui
ui -> ui2 : Transfer data with data selected
deactivate ui
activate ui2
ui2 -> ui2 : Hide all button & disable all field
ui2 -> api : request data with parameter id_request
deactivate ui2
activate api
api -> DB_PMO_IT : Get data
deactivate api
activate DB_PMO_IT
note left of DB_PMO_IT
    Get field
    "requestNumber", "referenceApplication", "projectTitle",
    "requestDate", "description", "picName",
    "status", "state", "ictNumber", "ictDate","priority"
    from table "request_project"

    Get field "title", "url"
    from table "reference"

    Get field "description", "impact", "mitigation"
    from table "risk_hazard"

    Get field
    "name", "presentTitle",
    "reason", "dateReason"
    from table "remark_log"

    Get all field
    from table "master_status"

    Get all field
    from table "master_project_type"

    Get field "priority"
    from table "project_type"

    Get field "organization", "smeName", "moduleFunction", "sign", "signDate"
    from table "assignment"

    Get field "reviewStatus", "reason", "businessImplementation", "functionalSpecification",
    "technicalSpecification", "implementationSolution", "timelineStartDate", "timelineEndDate",
    "timelineEffort", "timelineResource", "proposedCost",
    from table "fill_by_it"

    Get field
    "sourceOfBudget","budgetNumber"
    from table "request_project"

    Get field "link", "status", "documentTypeId"
    from table "document"

    filter by id_request_project
end note
api <- DB_PMO_IT : response data
deactivate DB_PMO_IT

activate api
api -> ui2 : return json
deactivate api
activate ui2
ui2 -> ui2 : Show button if
note right of ui2
    if login as user
    not show anything button
    if login as pmo & Manager TDI/TDO not yet approve
    enable all field & show button "submit"
    if login as manager TDI/TDO & SME not yet submit
    show button "submit"
    if login as manager TDI/TDO & SME has been submit
    show button "approve"
    if login as SM TDI/TDO & Manager has been approve
    show button "approve"
    if login as VP TD & SM has been approve
    show button "approve"
endnote
ui2 -> user : Display
deactivate ui2

@enduml