@startuml PMO IT
title "Flow Process Approve / Reject / Revise"

actor "user" as user #Yellow
' boundary "Need Approval Menu" as ui
boundary "Detail Page" as ui2
control "api" as api
database "DB_PMO_IT" as DB_PMO_IT

autonumber

group onClick button "Approve"
    user -> ui2 : click button "Approve"
    activate ui2
    ui2 -> api : put data value button
    deactivate ui2
    activate api
    api -> DB_PMO_IT : update
    deactivate api
    activate DB_PMO_IT
    note left of DB_PMO_IT
        Update field "id_status"
        from table "request_project"
    end note
    api <- DB_PMO_IT : response data
    deactivate DB_PMO_IT
    activate api
    alt Success
        ui2 <- api : return "Success" & reload page
        activate ui2
        user <- ui2 : show message "Success"
        deactivate ui2
    else else
        ui2 <- api : return message error
        deactivate api
        activate ui2
        user <- ui2 : show message error
        deactivate ui2
    end
end

group onClick button "Reject / Revise"
    user -> ui2 : Click button "Reject / Revise"
    activate ui2
    ui2 -> user : Show pop up "Reject / Revise form"
    deactivate ui2
    user -> ui2 : Fill data
    activate ui2
    user -> ui2 : click button "Confirm"
    ui2 -> api : put data value button
    deactivate ui2
    activate api
    api -> DB_PMO_IT : insert or update
    deactivate api
    activate DB_PMO_IT
    note left of DB_PMO_IT
        Update field "dateReason",
        "reason"
        from table "remark_log"

        Update field "status"
        from table "request_project"
    end note
    api <- DB_PMO_IT : response data
    deactivate DB_PMO_IT
    activate api
    alt Success
        ui2 <- api : return "Success" & reload page
        activate ui2
        user <- ui2 : show message "Success"
        deactivate ui2
    else else
        ui2 <- api : return message error
        deactivate api
        activate ui2
        user <- ui2 : show message error
        deactivate ui2
    end
end

@enduml