@startuml blog
title "Blog My Orbit"

actor "Customer" as C
boundary "FE Web" as FE
box "Microservices" #LightBlue
participant "Blog" as Content
end box
database "Pimcore" as DB

== Home ==

C -> FE : open page "blog.myorbit.id"
activate FE
group #LightGreen NEW
FE -> Content ++ :  list videos \nGET /ms/blog/v1/blog-video
end
Content -> DB ++ : get list data videos
DB --> Content --: response data videos
Content --> FE -- : response data videos
group #LightGreen NEW
FE -> Content ++ :  list article by parameter \nGET /ms/blog/v1/blog-article?sortby={sortby}&search={search}&tagby={tagby}
end
Content -> DB ++: get list data article
DB --> Content --: response data articles
Content --> FE -- : response data articles
FE -> C --: show data videos & articles
@enduml