@startuml blog
title "Process Filter Modem MyOrbit"


actor "Customer" as C
boundary "FE Web" as FE

box "BAU" #LightPink
participant "package-lumen" as Package
end box
database "Pimcore" as DBPimcore

== Filter Modem ==
C -> FE ++: Click button Apply
group #LightGreen NEW
FE -> Package ++ : filter modem \n POST /v1/products/{category_id}
end
Package -> DBPimcore ++: get list modem
DBPimcore --> Package --: response  list modem
Package --> FE -- : response list modem
FE -> C --: show list modem

C -> FE ++: Click button Apply
group #LightSalmon ENHANCE
FE -> Package ++ : package-categories\n GET /v6/product-categories
end
Package -> DBPimcore ++: get list modem
DBPimcore --> Package --: response  list modem
Package --> FE -- : response list modem
FE -> C --: show list modem
@enduml