@startuml "I Join - Advance Postpaid Activation"

title "I Join - Advance Postpaid Activation"

actor Customer as cust
boundary Website as web

box Microservices #LightBlue
participant Activation as msActivation
end box
box Legacy #LightPink
participant "Old\nMS Device" as msDevice
end box

participant ESB as esb


activate web
...
note over web
    Customer has filled Delivery Information
end note

== Determine Postpaid Registration Journey ==
group #LightGreen NEW
    web -> msActivation ++: GET check-eligibility msisdn\n/v1/check-eligibility/msisdn/{msisdn}
end
note over msActivation
    Use MyTelkomsel (Non Orbit, 
    Registered Tsel No) at Data Diri?
end note
msActivation -> msDevice ++: GET Product Warehouse \nBy msisdn
msActivation -> esb ++: GET customer profile \nBy msisdn
msDevice --> msActivation --: return is Modem or Not
esb --> msActivation --: return is Telkomsel & Registered or Not
    msActivation --> web --: return eligibility

alt MSISDN is eligible to be Referenced
    note over web #Black
        <color #FFF>FOR DETAIL, CHECK</color>
        <color #FFF><size:20>Advance Postpaid Regis </size></color>
        <color #FFF><size:20>Autofill JOURNEY</size></color>
    end note
else #LightPink MSISDN is NOT eligible to be Referenced
    note over web #Black
        <color #FFF><size:20>Advance Postpaid Regis </size></color>
        <color #FFF><size:20>Manual Input JOURNEY</size></color>
    end note

end

== Prompt to Advance Purchase Postpaid Regis==
group #LightGreen NEW
    web -> msActivation ++: GET Purchase Postpaid Regis by OrderUUID\n/v1/postpaid-registration/purchase/status
end
note over msActivation
    by:
    - orderUUID
end note
msActivation --> web --: return Postpaid Regis status


note over web
    If Registration Exists, show Download MyTsel

    If Registration Doesnt exist, prompt Postpaid Registration
end note


@enduml